import { rootAPI } from "@/_api";
import { APIEndpoints } from "../../../_api/core/constants";


const authApi = rootAPI.injectEndpoints({
    endpoints: (builder) => ({

        signup: builder.mutation<void, SignupRequest>({
            query: (body) => ({
                url: APIEndpoints.signup,
                method: "POST",
                body,
            }),
        }),

        login: builder.mutation<LoginResponse, LoginRequest>({
            query: (body) => ({
                url: APIEndpoints.login,
                method: "POST",
                body,
            }),
            invalidatesTags: ['USER']
        }),

        me: builder.query<{ user: AuthUser }, void>({
            query: () => ({
                url: APIEndpoints.me,
                method: "GET",
            }),
            providesTags: ["USER"],
        }),

    })
});

// Export hooks for your endpoints, this is used in the Login and Signup component, it is automatically generated by RTK Query
export const {
    useSignupMutation,
    useLoginMutation,
    useMeQuery,
} = authApi;